services:
  host-app:
    container_name: mfe-host-preview
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run preview -- --port 5000 --host 
    ports:
      - "5000:5000"
    # ⚠️ ATENÇÃO: NÃO monte volumes (.:/app) aqui se você quiser testar o build estático puro.
    # Se você mapear o volume local, a pasta dist gerada no container pode ser sobrescrevida ou apagada pela sua pasta local.