services:
  bff:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-bff
    ports:
      - "3000:3000"
    environment:
      BACKEND_BASE_URL: http://backend:8080/api
    networks:
      - back-network

networks:
  back-network:
    external: true # Diz ao Compose para usar a rede já criada pelo arquivo incluído
    name: shared-back-network