include:
  # - ./../mongoDB/docker-compose.yml
  - /var/home/dev/Documentos/Projetos/mySystem/mongoBD/docker-compose.yml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      MONGO_USER: mongoUser
      MONGO_PASSWORD: mongoPwd
      # Exemplo de URI para o Spring se conectar:
      SPRING_DATA_MONGODB_URI: mongodb://mongoUser:mongoPwd@mongodb:27017/admin
    networks:
      - mongo-network # Conecta o backend na mesma rede do banco
      - back-network
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  mongo-network:
    external: true # Diz ao Compose para usar a rede já criada pelo arquivo incluído
    name: shared-mongo-network
  back-network:
    driver: bridge