services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    # ports:
    #   - "8080:8080"
    environment:
      MONGO_USER: mongoUser
      MONGO_PASSWORD: mongoPwd
      # Exemplo de URI para o Spring se conectar:
      SPRING_DATA_MONGODB_URI: mongodb://mongoUser:mongoPwd@mongodb:27017/admin
    networks:
      - mongo-network # Conecta o backend na mesma rede do banco
      - back-network

networks:
  mongo-network:
    external: true # Diz ao Compose para usar a rede já criada pelo arquivo incluído
    name: shared-mongo-network
  back-network:
    name: shared-back-network
    driver: bridge